pull_request_rules:
  - name: automatic merge when GitHub branch protection passes + explicit two approvals
    conditions:
      - "#approved-reviews-by>=2"
      - base=master
    actions:
      merge:
        method: merge
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it? 🙏
