sudo: required
dist: trusty
services:
- docker
env:
  global:
  - COMMIT_AUTHOR_EMAIL=skynet@open.qa
  matrix:
  - FULLSTACK=0 UITESTS=0
  - FULLSTACK=0 UITESTS=1
  - GH_PUBLISH=true FULLSTACK=1
  - SCHEDULER_FULLSTACK=1
  - DEVELOPER_FULLSTACK=1
before_script:
- docker pull registry.opensuse.org/devel/openqa/containers/openqa_dev:latest
cache:
  directories:
  - assets/cache
script:
- mkdir -p assets/cache && chmod a+w assets/cache
- touch openqa-debug.log autoinst-log.txt && chmod a+w openqa-debug.log autoinst-log.txt
- sudo chown -R 1000:1000 assets/cache
# as long as we have some unfixed flaky tests we should let travis CI retry,
# not humans :)
# known issues:
# * 05-scheduler-full.t: https://progress.opensuse.org/issues/37628
# * 25-cache-service.t: https://progress.opensuse.org/issues/53858
# * ui/12-needle-edit.t: https://progress.opensuse.org/issues/37610
# * ui/18-tests-details.t: https://progress.opensuse.org/issues/38276
# * full-stack.t: https://progress.opensuse.org/issues/37638 and https://progress.opensuse.org/issues/54032
- travis_retry make prepare-and-launch-docker-to-run-tests-within
after_script:
- bash script/generate-documentation $encrypted_e2c381aa6b8c_key $encrypted_e2c381aa6b8c_iv
after_failure:
- cat openqa-debug.log
- cat autoinst-log.txt
