language: perl
perl:
  - "5.18"
before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/trusty.list
  - sudo apt-get update
install:
  - cpanm -nq Perl::Tidy
  - ./script/tidy --check
  - sudo apt-get install libgmp3-dev
  - cpanm -nq `cat DEPENDENCIES.txt` "Devel::Cover" "Devel::Cover::Report::Coveralls"
script:
  # - cover -test
  - PERL5OPT=-MDevel::Cover MOJO_LOG_LEVEL=debug OPENQA_LOGFILE=/tmp/openqa-debug.log prove -r
after_success:
  - cover -report coveralls
after_failure:
  - cat /tmp/openqa-debug.log
