language: perl
perl:
  - "5.18"
install:
  - sudo apt-get install libgmp3-dev
  - cpanm -nq `grep -v Image::Magick DEPENDENCIES.txt`
  - cpanm -nq "Devel::Cover" "Devel::Cover::Report::Coveralls"
script:
  # - cover -test
  - PERL5OPT=-MDevel::Cover prove -r
after_success:
  - cover -report coveralls
