sudo: false
dist: trusty
services:
  - docker
env:
  global:
    - COMMIT_AUTHOR_EMAIL=skynet@open.qa
  matrix:
    - FULLSTACK=0 UITESTS=0
    - FULLSTACK=0 UITESTS=1
    - GH_PUBLISH=true FULLSTACK=1
    - SCHEDULER_FULLSTACK=1
before_install: yes
install: yes
before_script:
  - docker pull dasantiago/openqa-tests  
script:
  - docker run --name=openqa-tests -v $TRAVIS_BUILD_DIR:/opt/openqa -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /var/run/dbus:/var/run/dbus dasantiago/openqa-tests make travis-codecov
after_failure:
  - cat /tmp/openqa-debug.log
after_script: yes
