language: perl
perl:
  - "5.18"
before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/trusty.list
  - sudo apt-get update
install:
  - sudo apt-get install libgmp3-dev libdbus-1-dev
  - cpanm -nq --installdeps --with-feature=coverage .
  - gem install sass
script:
  - make checkstyle
  - COVERAGE_REPORT=coveralls make coverage
after_failure:
  - cat /tmp/openqa-debug.log
