language: perl
perl:
  - "5.18"
install:
  - sudo apt-get install libgmp3-dev
  - cpanm -nq `grep -v Image::Magick DEPENDENCIES.txt`
  - cpanm -nq "Devel::Cover" "Devel::Cover::Report::Coveralls"
  - ./script/initdb
script:
  - cover -test
after_success:
  - cover -report coveralls
