language: perl
perl:
  - "5.18"
install:
  - sudo apt-get install libgmp3-dev
  - cpanm -nq `grep -v Image::Magick DEPENDENCIES.txt`
  - cpanm -nq "Devel::Cover" "Devel::Cover::Report::Coveralls"
script:
  # - cover -test
  - PERL5OPT=-MDevel::Cover MOJO_LOG_LEVEL=debug OPENQA_LOGFILE=/tmp/openqa-debug.log prove -r
after_success:
  - cover -report coveralls
after_failure:
  - cat /tmp/openqa-debug.log
