codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  notify:
    irc:
      default:
        server: chat.freenode.irc
	channel: #opensuse-factory
  status:
    changes: false
    project:
      target: 69.2
      only_pulls: true
    patch: false
