version: '3.8'

services:
  scheduler:
    image: openqa_webui
    volumes: &volumes
      - ./workdir/data/factory/iso:/data/factory/iso:rw
      - ./workdir/data/factory/hdd:/data/factory/hdd:rw
      - ./workdir/data/factory/other:/data/factory/other:rw
      - ./workdir/data/factory/tmp:/data/factory/tmp:rw
      - ./workdir/data/testresults:/data/testresults:rw
      - ./workdir/data/tests:/data/tests:ro
      - ./conf:/data/conf:ro
    environment:
      MODE: "scheduler"
      MOJO_LISTEN: "http://0.0.0.0:9529"
    depends_on:
      - db

  websockets:
    image: openqa_webui
    build: .
    ports:
      - "9527:9527"  # worker connection
    volumes: *volumes
    environment:
      MODE: "websockets"
      MOJO_LISTEN: "http://0.0.0.0:9527"
    depends_on:
      - db

  gru:
    image: openqa_webui
    build: .
    volumes: *volumes
    environment:
      MODE: "gru"
    depends_on:
      - db

  livehandler:
    image: openqa_webui
    build: .
    ports:
      - "9528:9528"  # handle live view
    volumes: *volumes
    environment:
      MODE: "livehandler"
      MOJO_LISTEN: "http://0.0.0.0:9528"
    depends_on:
      - db

  webui:
    image: openqa_webui
    build: .
    ports:
      - "9526"
    volumes: *volumes
    environment:
      MODE: "webui"
      MOJO_LISTEN: "http://0.0.0.0:9526"
    depends_on:
      - db
    deploy:
      replicas: ${OPENQA_WEBUI_REPLICAS}
    entrypoint: "sh -c 'chmod -R a+rwX /data/{factory,testresults}; /root/run_openqa.sh'"


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: openqa
      POSTGRES_USER: openqa
      POSTGRES_DB: openqa
    volumes:
      - ./workdir/db:/var/lib/postgresql/data

  nginx:
    image: openqa_webui_lb
    build:
      context: .
      dockerfile: Dockerfile-lb
    restart: always
    ports:
      - "9526:9526"
      # Uncomment for SSL access
      # - "443:443"
    environment:
      replicas: ${OPENQA_WEBUI_REPLICAS}
      # If is needed to set a certificate for SSL
      # - cert.crt:/etc/ssl/certs/opeqa.crt
      # - cert.key:/etc/ssl/certs/opeqa.key
